name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Codecov Node
      uses: iansu/codecov-action-node@v1.0.0
#       with:
        # Repository upload token - get it from codecov.io
#         token: # optional
    - name: Readable Readme
      uses: tianhaoz95/readable-readme@v0.1.7-alpha
#       with:
#         # Input to use
#         myInput: # optional, default is world
#         # The token of the GitHub identity that report should be posted from
#         token: # optional
